version: '3'

networks:
  xxl-job:

services:
  # db
  mysql:
    image: mysql
    container_name: mysql
    hostname: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_pwd
    volumes:
    - ./initdb:/docker-entrypoint-initdb.d
    networks:
    - xxl-job
    ports:
    - '13306:3306'
    command: --default-authentication-plugin=mysql_native_password

  # 调度中心
  xxl-job-admin:
    image: xuxueli/xxl-job-admin:2.1.2
    container_name: xxl-job-admin
    hostname: xxl-job-admin
    depends_on:
    - mysql
    environment:
    - PARAMS=--spring.datasource.url=jdbc:mysql://mysql:3306/xxl_job?Unicode=true&characterEncoding=UTF-8
    networks:
    - xxl-job
    ports:
    - '8080:8080'